### ISSUE TITLE
正在加载大图时，可否增加点击退出 && 偶现大图不显示

### ISSUE THREAD

**Issue by andyxialm** [andforce/iBeebo#5]
测试结果: 
1. 点击图片，加载大图页面，默认全屏，此时若想退出，须手动换出NavigationBar，back
直接点击图片无法back，而加载完成后点击图片可以back。
2. 偶现，点击缩略图显示大图时，缩略图显示，而大图界面进度条走完后黑屏(无图片显示)。而此时不可点击界面退出。同上

期望结果: 正在加载中的大图，也可以点击退出。

**Comment by andforce** [comment]
@andyxialm 最近没有维护这个项目，等有时间再处理，抱歉啦
